# Generated by Django 2.1.7 on 2019-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweepstakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='')),
                ('background', models.ImageField(upload_to='')),
                ('disclaimer', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Lotteries',
            },
        ),
    ]
