# Generated by Django 2.1.7 on 2019-05-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sweepstakes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweepstakes',
            options={'verbose_name_plural': 'Sweepstakes'},
        ),
        migrations.RemoveField(
            model_name='sweepstakes',
            name='status',
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='current',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
