# Generated by Django 2.1.7 on 2019-05-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0009_auto_20190530_2026'),
        ('home', '0003_auto_20190526_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweepWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windate', models.CharField(max_length=100)),
                ('sweep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sweepstakes')),
            ],
            options={
                'verbose_name_plural': 'SweepstakesWinner',
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('sweep_ids', models.CharField(max_length=100)),
                ('active_sweep', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customauth.MyUser')),
            ],
            options={
                'verbose_name_plural': 'Sweepstakes',
            },
        ),
        migrations.AddField(
            model_name='sweepwinner',
            name='tablet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tablet'),
        ),
    ]
