# Generated by Django 2.1.7 on 2019-05-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190530_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
