# Generated by Django 2.1.7 on 2019-05-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190530_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customauth.MyUser'),
        ),
    ]
