# Generated by Django 2.1.7 on 2019-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190604_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='po_box_unit_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='PO Box/Unit Number'),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='suite',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
