# Generated by Django 2.1.7 on 2019-06-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190613_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweepuser',
            name='check_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
