# Generated by Django 2.1.7 on 2019-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190613_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='confirm_password',
            field=models.CharField(default='', max_length=100, verbose_name='Confirm Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablet',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
