# Generated by Django 2.1.7 on 2019-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190616_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweepstakes',
            name='enddate',
            field=models.DateTimeField(help_text='Time is in UTC'),
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='startdate',
            field=models.DateTimeField(help_text='Time is in UTC'),
        ),
    ]
