# Generated by Django 2.1.7 on 2019-06-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190618_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweepstakes',
            name='fontsize',
            field=models.IntegerField(default=13, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='enddate',
            field=models.DateTimeField(help_text='Time is in UTC - 5'),
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='startdate',
            field=models.DateTimeField(help_text='Time is in UTC - 5'),
        ),
    ]
