# Generated by Django 2.1.7 on 2019-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190621_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='login_status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
