# Generated by Django 2.1.7 on 2019-06-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_tablet_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]
