# Generated by Django 2.1.7 on 2019-06-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190627_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweepuser',
            name='checkEmail',
            field=models.BooleanField(default=False, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='checkSMS',
            field=models.BooleanField(default=False, verbose_name='SMS'),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='po_box_unit_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='PO Box/Unit Number'),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='suite',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
