# Generated by Django 2.1.7 on 2019-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190627_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablet',
            options={'verbose_name_plural': 'tablet'},
        ),
        migrations.AlterField(
            model_name='sweepcheckin',
            name='check_time',
            field=models.DateTimeField(),
        ),
    ]
