# Generated by Django 2.1.7 on 2019-07-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190722_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweepwinner',
            name='windate',
            field=models.DateTimeField(),
        ),
    ]
