# Generated by Django 2.1.7 on 2019-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190722_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweepuser',
            name='po_box_unit_number',
        ),
        migrations.RemoveField(
            model_name='sweepuser',
            name='suite',
        ),
        migrations.AddField(
            model_name='sweepuser',
            name='suite_po_box',
            field=models.CharField(default='', max_length=50, verbose_name='Suite/PO Box'),
        ),
    ]
