# Generated by Django 2.1.7 on 2019-11-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20191102_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweepstakes',
            name='button_header_font_color',
            field=models.CharField(default='', max_length=7, verbose_name='Button/Header Font Hex Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='button_header_hex_color',
            field=models.CharField(default='', max_length=7, verbose_name='Button/Header Hex Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='disclaimer_color',
            field=models.CharField(default='', max_length=7, verbose_name='Disclaimer Font Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='header_font_size',
            field=models.IntegerField(default=0, verbose_name='Header Font Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='header_hex_color',
            field=models.CharField(default='', max_length=7, verbose_name='Header Hex Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='header_text',
            field=models.CharField(default='', max_length=100, verbose_name='Header Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FM', 'Federated States Of Micronesia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MH', 'Marshall Islands'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PW', 'Palau'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='IL', max_length=50),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
