# Generated by Django 2.1.7 on 2019-11-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question_count',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, max_length=2, verbose_name='Number of Questions'),
        ),
    ]
