# Generated by Django 2.1.7 on 2019-11-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_survey_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question_text',
            new_name='question_text1',
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text10',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text2',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text3',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text4',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text5',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text6',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text7',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text8',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_text9',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type1',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type10',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type2',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type3',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type4',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type5',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type6',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type7',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type8',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question_type9',
            field=models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], default='', max_length=10, verbose_name='Question 9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_count',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=2, verbose_name='Number of Questions'),
        ),
    ]
