# Generated by Django 2.1.7 on 2019-11-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20191122_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweepstakes',
            name='background_image_after_sweepstake',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='background_image_after_sweepstake_check',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='border_hightlight_hex_color',
            field=models.CharField(default='', max_length=7, verbose_name='Border/Highlight Hex Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='customer_checkin_frequency',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='primary_hex_color',
            field=models.CharField(default='', max_length=7, verbose_name='Primary Hex Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='prioritize_sweepstakes',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='survey1_check',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='survey1_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey1_name', to='home.Survey'),
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='survey2_check',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweepstakes',
            name='survey2_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey2_name', to='home.Survey'),
        ),
    ]
