# Generated by Django 2.1.7 on 2019-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20191124_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweepstakes',
            name='background_image_after_sweepstake',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
