# Generated by Django 2.1.7 on 2019-12-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20191201_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_image', models.ImageField(upload_to='')),
                ('option_tag', models.CharField(max_length=100)),
                ('option_complete', models.CharField(choices=[('goto', 'If selected, go to question '), ('complete', 'If selected, complete survey')], max_length=10, verbose_name='')),
                ('option_goquestion', models.CharField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=10, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('option_complete', models.CharField(choices=[('goto', 'If selected, go to question '), ('complete', 'If selected, complete survey')], max_length=10, verbose_name='')),
                ('option_goquestion', models.CharField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=10, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'surveyanswertext',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('type_1', 'Multiple Choice'), ('type_2', 'Multiple Choice (Images)')], max_length=10, verbose_name='Question 1')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('options_count', models.CharField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=10, verbose_name='Number of Options')),
            ],
            options={
                'verbose_name_plural': 'surveyquestion',
            },
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text10',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text6',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text7',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text8',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_text9',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type10',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type6',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type7',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type8',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_type9',
        ),
        migrations.AddField(
            model_name='surveyanswertext',
            name='option_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='surveyanswerimage',
            name='option_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question1', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question10', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question2', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question3', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question4', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question5', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question6', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question7', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question8', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question9', to='home.SurveyQuestions'),
        ),
    ]
