# Generated by Django 2.1.7 on 2019-12-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_survey_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question9',
        ),
        migrations.AddField(
            model_name='survey',
            name='question_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_1', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_10', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_2', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_3', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_4', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_5', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_6', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_7', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_8', to='home.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_9', to='home.SurveyQuestions'),
        ),
    ]
