# Generated by Django 2.1.7 on 2019-12-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20191202_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question_count',
            new_name='questions_count',
        ),
    ]
