# Generated by Django 2.1.7 on 2019-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20191203_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyanswerimage',
            options={'verbose_name_plural': 'surveyanswerimage'},
        ),
        migrations.AddField(
            model_name='surveyanswerimage',
            name='question_number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='surveyanswerimage',
            name='survey_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
