# Generated by Django 2.1.7 on 2019-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20191206_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweepuser',
            name='suite_po_box',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Suite/PO Box'),
        ),
    ]
