# Generated by Django 2.1.7 on 2019-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20191209_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweepuser',
            name='survey_enter_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
