# Generated by Django 2.1.7 on 2019-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_sweepuser_survey_enter_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweepuser',
            name='survey_enter_time',
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_enter_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sweepcheckin',
            name='check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
