# Generated by Django 2.1.7 on 2019-12-17 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20191211_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweepuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 4, 55, 28, 381716), verbose_name='Created'),
        ),
    ]
