# Generated by Django 2.1.7 on 2019-12-22 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_sweepuser_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_10',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_7',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_8',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweepcheckin',
            name='survey_question_9',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 9, 23, 40, 826462), verbose_name='Created'),
        ),
    ]
