# Generated by Django 2.2.9 on 2020-01-11 02:46

import datetime
from django.db import migrations, models
import django.utils.timezone
import home.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20191222_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        )
    ]
