# Generated by Django 2.2.9 on 2020-01-11 02:46

import datetime
from django.db import migrations, models
import django.utils.timezone
import home.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20191222_0923'),
    ]

    operations = [
    ]
