# Generated by Django 2.2.9 on 2020-01-10 16:06

import datetime
from django.db import migrations, models
import django.utils.timezone
import home.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20191222_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='background_image_after_sweepstake',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=home.models.Sweepstakes.file_name, validators=[home.models.validate_image]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='logo',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=home.models.Sweepstakes.file_name, validators=[home.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 10, 4, 21, 56221), verbose_name='Created'),
        ),
    ]
