# Generated by Django 2.2.9 on 2020-02-10 13:30

from django.db import migrations, models
import django.utils.timezone
import home.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20200110_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweepstakes',
            name='background',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=home.models.Sweepstakes.file_name, validators=[home.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='background_image_after_sweepstake',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=home.models.Sweepstakes.file_name, validators=[home.models.validate_image]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='enddate',
            field=models.DateTimeField(help_text='Time is in UTC - 6'),
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='logo',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=home.models.Sweepstakes.file_name, validators=[home.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='sweepstakes',
            name='startdate',
            field=models.DateTimeField(help_text='Time is in UTC - 6'),
        ),
        migrations.AlterField(
            model_name='sweepuser',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
