# Generated by Django 2.1.7 on 2019-05-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('address', models.TextField()),
                ('last_name', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
                ('phone', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('tablet_id', models.TextField()),
                ('check_time', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
