# Generated by Django 2.1.7 on 2019-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='check_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='tablet_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(max_length=50),
        ),
    ]
