# Generated by Django 2.1.7 on 2019-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_auto_20190523_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='sweep_ids',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
