# Generated by Django 2.1.7 on 2019-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_myuser_active_sweep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='label',
            field=models.CharField(default='Added by Admin', max_length=100),
        ),
    ]
