# Generated by Django 2.1.7 on 2019-05-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0006_auto_20190530_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='po_box',
            new_name='po_box_unit_number',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='unit_number',
        ),
    ]
