# Generated by Django 2.1.7 on 2019-05-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0008_auto_20190530_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='active_sweep',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sweep_ids',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(help_text='Please input Phone No in this format ( ex: 1234566788 )', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='po_box_unit_number',
            field=models.CharField(max_length=50, verbose_name='PO Box/Unit Number'),
        ),
    ]
