# Generated by Django 2.1.7 on 2019-05-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0009_auto_20190530_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tablet_id',
        ),
    ]
