# Generated by Django 2.1.7 on 2019-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0010_remove_myuser_tablet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(help_text='Please input Phone No in this format ( ex: 12345667889 or 2345678890)', max_length=50, unique=True),
        ),
    ]
